"""
CIAF Watermarks Module Tests

Comprehensive test suite for the CIAF watermarking framework:
- Artifact types and watermark types
- Dual-state hashing (before/after watermark)
- Forensic DNA fragments (text, image, video, audio)
- Artifact evidence and verification
- Watermark removal detection
- Perceptual hashing and similarity matching

Created: 2026-03-31
Version: 1.0.0
"""

import pytest
from datetime import datetime, timezone
import hashlib

from ciaf.watermarks import (
    ArtifactType,
    WatermarkType,
    ArtifactFingerprint,
    WatermarkDescriptor,
    ForensicFragment,
    TextForensicFragment,
    ImageForensicFragment,
    VideoForensicSnippet,
    AudioForensicSegment,
    ForensicFragmentSet,
    ArtifactHashSet,
    ArtifactEvidence,
    VerificationResult,
    ForensicArtifactProfile,
    sha256_text,
    sha256_bytes,
    canonical_json,
)


class TestArtifactTypes:
    """Test ArtifactType enumeration."""

    def test_artifact_types_exist(self):
        """Test all artifact types are defined."""
        assert ArtifactType.TEXT == "text"
        assert ArtifactType.IMAGE == "image"
        assert ArtifactType.PDF == "pdf"
        assert ArtifactType.JSON == "json"
        assert ArtifactType.BINARY == "binary"
        assert ArtifactType.VIDEO == "video"
        assert ArtifactType.AUDIO == "audio"


class TestWatermarkTypes:
    """Test WatermarkType enumeration."""

    def test_watermark_types_exist(self):
        """Test all watermark types are defined."""
        assert WatermarkType.NONE == "none"
        assert WatermarkType.VISIBLE == "visible"
        assert WatermarkType.METADATA == "metadata"
        assert WatermarkType.EMBEDDED == "embedded"
        assert WatermarkType.HYBRID == "hybrid"
        assert WatermarkType.QR_CODE == "qr_code"


class TestWatermarkDescriptor:
    """Test WatermarkDescriptor model."""

    def test_create_watermark_descriptor(self):
        """Test creating a watermark descriptor."""
        watermark = WatermarkDescriptor(
            watermark_id="wm_001",
            watermark_type=WatermarkType.VISIBLE,
            tag_text="Generated by AI | Verify: vault.example.com",
            verification_url="https://vault.example.com/verify/wm_001",
            removal_resistance="low",
            location="bottom_right",
        )

        assert watermark.watermark_id == "wm_001"
        assert watermark.watermark_type == WatermarkType.VISIBLE
        assert "vault.example.com" in watermark.tag_text
        assert watermark.removal_resistance == "low"

    def test_watermark_descriptor_to_dict(self):
        """Test converting watermark descriptor to dictionary."""
        watermark = WatermarkDescriptor(
            watermark_id="wm_002",
            watermark_type=WatermarkType.HYBRID,
            embed_method="LSB steganography + XMP metadata",
            removal_resistance="high",
        )

        watermark_dict = watermark.to_dict()
        assert watermark_dict["watermark_id"] == "wm_002"
        assert watermark_dict["watermark_type"] == "hybrid"
        assert watermark_dict["removal_resistance"] == "high"


class TestArtifactFingerprint:
    """Test ArtifactFingerprint model."""

    def test_create_perceptual_fingerprint(self):
        """Test creating a perceptual hash fingerprint."""
        fingerprint = ArtifactFingerprint(
            algorithm="perceptual_hash",
            value="8f3a7b2c9e1d4f6a",
            role="perceptual",
            confidence=0.95,
        )

        assert fingerprint.algorithm == "perceptual_hash"
        assert fingerprint.role == "perceptual"
        assert fingerprint.confidence == 0.95

    def test_create_simhash_fingerprint(self):
        """Test creating a simhash fingerprint for text."""
        fingerprint = ArtifactFingerprint(
            algorithm="simhash",
            value="a3f8b2c9e1d4f7a6",
            role="text_similarity",
            confidence=0.92,
        )

        assert fingerprint.algorithm == "simhash"
        assert fingerprint.role == "text_similarity"


class TestTextForensicFragment:
    """Test TextForensicFragment model."""

    def test_create_text_fragment(self):
        """Test creating a text forensic fragment."""
        original_text = "This is a high-entropy beginning section of AI-generated content."
        watermarked_text = original_text + " [AI-Generated]"

        fragment = TextForensicFragment(
            fragment_id="frag_0_begin",
            fragment_type="text",
            entropy_score=0.87,
            sampling_method="begin",
            content_position=0,
            offset_start=0,
            offset_end=len(original_text),
            fragment_length=len(original_text),
            sample_location="beginning",
            fragment_text=original_text,
            fragment_hash_before=sha256_text(original_text),
            fragment_hash_after=sha256_text(watermarked_text[: len(original_text)]),
        )

        assert fragment.fragment_id == "frag_0_begin"
        assert fragment.entropy_score == 0.87
        assert fragment.sample_location == "beginning"
        assert fragment.fragment_length == len(original_text)
        assert len(fragment.fragment_hash_before) == 64  # SHA-256 hex digest

    def test_text_fragment_multi_point_sampling(self):
        """Test multi-point sampling strategy for text."""
        text = "A" * 1000  # 1000 character text

        # Beginning fragment
        frag_begin = TextForensicFragment(
            fragment_id="frag_0_begin",
            fragment_type="text",
            entropy_score=0.85,
            sampling_method="begin",
            content_position=0,
            offset_start=0,
            offset_end=300,
            fragment_length=300,
            sample_location="beginning",
            fragment_text=text[0:300],
            fragment_hash_before=sha256_text(text[0:300]),
            fragment_hash_after=sha256_text(text[0:300]),
        )

        # Middle fragment
        frag_middle = TextForensicFragment(
            fragment_id="frag_1_middle",
            fragment_type="text",
            entropy_score=0.82,
            sampling_method="middle",
            content_position=400,
            offset_start=400,
            offset_end=700,
            fragment_length=300,
            sample_location="middle",
            fragment_text=text[400:700],
            fragment_hash_before=sha256_text(text[400:700]),
            fragment_hash_after=sha256_text(text[400:700]),
        )

        # End fragment
        frag_end = TextForensicFragment(
            fragment_id="frag_2_end",
            fragment_type="text",
            entropy_score=0.88,
            sampling_method="end",
            content_position=700,
            offset_start=700,
            offset_end=1000,
            fragment_length=300,
            sample_location="end",
            fragment_text=text[700:1000],
            fragment_hash_before=sha256_text(text[700:1000]),
            fragment_hash_after=sha256_text(text[700:1000]),
        )

        assert frag_begin.sample_location == "beginning"
        assert frag_middle.sample_location == "middle"
        assert frag_end.sample_location == "end"


class TestImageForensicFragment:
    """Test ImageForensicFragment model."""

    def test_create_image_fragment(self):
        """Test creating an image forensic fragment."""
        fragment = ImageForensicFragment(
            fragment_id="patch_2_4",
            fragment_type="image_patch",
            entropy_score=0.92,
            sampling_method="spatial",
            content_position=20,
            patch_grid_position="grid_2_4",
            patch_hash_before="8f3a7b2c9e1d4f6a",
            patch_hash_after="1d6e9c4a8b3f7e2d",
            region_coordinates=(128, 192, 64, 64),
        )

        assert fragment.patch_grid_position == "grid_2_4"
        assert fragment.entropy_score == 0.92
        assert fragment.region_coordinates == (128, 192, 64, 64)

    def test_image_fragment_alternative_hashes(self):
        """Test image fragment with alternative hash types."""
        fragment = ImageForensicFragment(
            fragment_id="patch_0_0",
            fragment_type="image_patch",
            entropy_score=0.89,
            sampling_method="spatial",
            content_position=0,
            patch_grid_position="grid_0_0",
            patch_hash_before="a3f8b2c9e1d4f7a6",
            patch_hash_after="d7e1c9a4f8b3e2d6",
            patch_ahash_before="8f3a7b2c",
            patch_dhash_before="9e1d4f6a",
            patch_whash_before="c4b8e2d7",
        )

        assert fragment.patch_ahash_before == "8f3a7b2c"
        assert fragment.patch_dhash_before == "9e1d4f6a"
        assert fragment.patch_whash_before == "c4b8e2d7"


class TestVideoForensicSnippet:
    """Test VideoForensicSnippet model."""

    def test_create_video_snippet(self):
        """Test creating a video forensic snippet."""
        snippet = VideoForensicSnippet(
            fragment_id="keyframe_2500ms",
            fragment_type="video_frame",
            entropy_score=0.89,
            sampling_method="temporal",
            content_position=75,
            timestamp_ms=2500,
            frame_index=75,
            frame_type="I-Frame",
            frame_duration_ms=33,
            frame_patch_hashes=["a8d3e7f2", "f2e7c4b9", "c4b9a8d3"],
            temporal_motion_hash="9f3e2a7c8d1b4f6e",
            motion_confidence=0.91,
        )

        assert snippet.timestamp_ms == 2500
        assert snippet.frame_type == "I-Frame"
        assert len(snippet.frame_patch_hashes) == 3
        assert snippet.motion_confidence == 0.91


class TestAudioForensicSegment:
    """Test AudioForensicSegment model."""

    def test_create_audio_segment(self):
        """Test creating an audio forensic segment."""
        segment = AudioForensicSegment(
            fragment_id="audio_5000ms",
            fragment_type="audio_segment",
            entropy_score=0.84,
            sampling_method="temporal",
            content_position=5000,
            start_time_ms=5000,
            segment_duration_ms=3000,
            spectrogram_hash="7a2f8d3e9c1b4f6a",
            frequency_centroid=1250.0,
            spectral_flatness=0.72,
            spectrogram_hash_before="e3b9c4d7a8f2e1d6",
            spectrogram_hash_after="4c7a9e2d8b3f1e6d",
        )

        assert segment.start_time_ms == 5000
        assert segment.segment_duration_ms == 3000
        assert segment.frequency_centroid == 1250.0
        assert segment.spectral_flatness == 0.72


class TestForensicFragmentSet:
    """Test ForensicFragmentSet collection."""

    def test_create_fragment_set_text(self):
        """Test creating a fragment set for text."""
        fragments = [
            TextForensicFragment(
                fragment_id=f"frag_{i}",
                fragment_type="text",
                entropy_score=0.85 + i * 0.02,
                sampling_method="multi_point",
                content_position=i * 300,
                offset_start=i * 300,
                offset_end=(i + 1) * 300,
                fragment_length=300,
                sample_location=["beginning", "middle", "end"][i],
                fragment_text=f"Fragment text {i}",
                fragment_hash_before=sha256_text(f"frag{i}_before"),
                fragment_hash_after=sha256_text(f"frag{i}_after"),
            )
            for i in range(3)
        ]

        fragment_set = ForensicFragmentSet(
            fragment_count=3,
            sampling_strategy="multi_point",
            total_coverage_percent=15.0,
            text_fragments=fragments,
            min_entropy_threshold=0.6,
            cumulative_entropy_score=0.88,
        )

        assert fragment_set.fragment_count == 3
        assert len(fragment_set.text_fragments) == 3
        assert fragment_set.cumulative_entropy_score == 0.88
        assert len(fragment_set.all_fragments) == 3


class TestArtifactHashSet:
    """Test ArtifactHashSet dual-state hashing."""

    def test_create_hash_set(self):
        """Test creating an artifact hash set."""
        original_content = b"This is the original AI-generated content."
        watermarked_content = (
            b"This is the original AI-generated content. [AI-Generated]"
        )

        hash_set = ArtifactHashSet(
            content_hash_before_watermark=sha256_bytes(original_content),
            content_hash_after_watermark=sha256_bytes(watermarked_content),
        )

        assert len(hash_set.content_hash_before_watermark) == 64
        assert len(hash_set.content_hash_after_watermark) == 64
        assert (
            hash_set.content_hash_before_watermark
            != hash_set.content_hash_after_watermark
        )

    def test_hash_set_with_forensic_fragments(self):
        """Test hash set with forensic fragments."""
        fragments = ForensicFragmentSet(
            fragment_count=3,
            sampling_strategy="multi_point",
            total_coverage_percent=15.0,
            text_fragments=[
                TextForensicFragment(
                    fragment_id="frag_0",
                    fragment_type="text",
                    entropy_score=0.87,
                    sampling_method="begin",
                    content_position=0,
                    offset_start=0,
                    offset_end=300,
                    fragment_length=300,
                    sample_location="beginning",
                    fragment_text="Fragment text",
                    fragment_hash_before=sha256_text("frag_before"),
                    fragment_hash_after=sha256_text("frag_after"),
                )
            ],
        )

        hash_set = ArtifactHashSet(
            content_hash_before_watermark=sha256_bytes(b"before"),
            content_hash_after_watermark=sha256_bytes(b"after"),
            forensic_fragments=fragments,
        )

        assert hash_set.forensic_fragments is not None
        assert len(hash_set.forensic_fragments.text_fragments) == 1


class TestArtifactEvidence:
    """Test ArtifactEvidence complete record."""

    def test_create_artifact_evidence(self):
        """Test creating complete artifact evidence."""
        watermark = WatermarkDescriptor(
            watermark_id="wm_001",
            watermark_type=WatermarkType.VISIBLE,
            tag_text="AI-Generated",
        )

        hashes = ArtifactHashSet(
            content_hash_before_watermark=sha256_bytes(b"original"),
            content_hash_after_watermark=sha256_bytes(b"watermarked"),
        )

        evidence = ArtifactEvidence(
            artifact_id="art_001",
            artifact_type=ArtifactType.TEXT,
            mime_type="text/plain",
            created_at=datetime.now(timezone.utc).isoformat(),
            model_id="gpt-4",
            model_version="4.0",
            actor_id="user_alice",
            prompt_hash=sha256_text("Write a story"),
            output_hash_raw=sha256_bytes(b"original"),
            output_hash_distributed=sha256_bytes(b"watermarked"),
            watermark=watermark,
            hashes=hashes,
        )

        assert evidence.artifact_id == "art_001"
        assert evidence.artifact_type == ArtifactType.TEXT
        assert evidence.model_id == "gpt-4"
        assert evidence.watermark.watermark_id == "wm_001"

    def test_artifact_evidence_canonical_bytes(self):
        """Test generating canonical bytes for signing."""
        watermark = WatermarkDescriptor(
            watermark_id="wm_002",
            watermark_type=WatermarkType.METADATA,
        )

        hashes = ArtifactHashSet(
            content_hash_before_watermark=sha256_bytes(b"before"),
            content_hash_after_watermark=sha256_bytes(b"after"),
        )

        evidence = ArtifactEvidence(
            artifact_id="art_002",
            artifact_type=ArtifactType.IMAGE,
            mime_type="image/png",
            created_at="2026-03-31T10:00:00Z",
            model_id="stable-diffusion",
            model_version="3.0",
            actor_id="user_bob",
            prompt_hash=sha256_text("A sunset"),
            output_hash_raw=sha256_bytes(b"image_before"),
            output_hash_distributed=sha256_bytes(b"image_after"),
            watermark=watermark,
            hashes=hashes,
        )

        canonical_bytes = evidence.to_canonical_bytes()
        assert isinstance(canonical_bytes, bytes)
        assert len(canonical_bytes) > 0

    def test_artifact_evidence_receipt_hash(self):
        """Test computing receipt hash."""
        watermark = WatermarkDescriptor(
            watermark_id="wm_003",
            watermark_type=WatermarkType.HYBRID,
        )

        hashes = ArtifactHashSet(
            content_hash_before_watermark=sha256_bytes(b"content_before"),
            content_hash_after_watermark=sha256_bytes(b"content_after"),
        )

        evidence = ArtifactEvidence(
            artifact_id="art_003",
            artifact_type=ArtifactType.PDF,
            mime_type="application/pdf",
            created_at="2026-03-31T10:00:00Z",
            model_id="ai-doc-gen",
            model_version="2.0",
            actor_id="user_charlie",
            prompt_hash=sha256_text("Generate report"),
            output_hash_raw=sha256_bytes(b"pdf_before"),
            output_hash_distributed=sha256_bytes(b"pdf_after"),
            watermark=watermark,
            hashes=hashes,
        )

        receipt_hash = evidence.compute_receipt_hash()
        assert len(receipt_hash) == 64  # SHA-256 hex digest


class TestVerificationResult:
    """Test VerificationResult for artifact verification."""

    def test_verification_exact_match_after_watermark(self):
        """Test verification with exact match to distributed version."""
        result = VerificationResult(
            artifact_id="art_001",
            exact_match_after_watermark=True,
            exact_match_before_watermark=False,
            likely_tag_removed=False,
            watermark_present=True,
            watermark_intact=True,
            confidence=1.0,
            notes=["Exact match to distributed version"],
        )

        assert result.is_authentic() is True
        assert result.exact_match_after_watermark is True
        assert result.watermark_intact is True

    def test_verification_watermark_removed(self):
        """Test verification detecting watermark removal."""
        result = VerificationResult(
            artifact_id="art_002",
            exact_match_after_watermark=False,
            exact_match_before_watermark=True,
            likely_tag_removed=True,
            watermark_present=False,
            watermark_intact=False,
            confidence=1.0,
            notes=["WATERMARK REMOVED: Matches pre-watermark version"],
        )

        assert result.is_authentic() is True
        assert result.likely_tag_removed is True
        assert result.watermark_present is False

    def test_verification_similarity_match(self):
        """Test verification with high similarity score."""
        result = VerificationResult(
            artifact_id="art_003",
            exact_match_after_watermark=False,
            exact_match_before_watermark=False,
            likely_tag_removed=False,
            perceptual_similarity_score=0.95,
            content_modified=True,
            confidence=0.95,
            notes=["High perceptual similarity (95%)"],
        )

        assert result.is_authentic() is True
        assert result.perceptual_similarity_score == 0.95

    def test_verification_not_authentic(self):
        """Test verification rejecting non-authentic artifact."""
        result = VerificationResult(
            artifact_id="unknown",
            exact_match_after_watermark=False,
            exact_match_before_watermark=False,
            likely_tag_removed=False,
            perceptual_similarity_score=0.3,
            confidence=0.0,
            notes=["No matching evidence found"],
        )

        assert result.is_authentic() is False


class TestForensicArtifactProfile:
    """Test ForensicArtifactProfile extended model."""

    def test_create_forensic_profile(self):
        """Test creating extended forensic profile."""
        profile = ForensicArtifactProfile(
            exact_hash_before_watermark=sha256_bytes(b"before"),
            exact_hash_after_watermark=sha256_bytes(b"after"),
            normalized_hash_before_watermark=sha256_bytes(b"normalized_before"),
            normalized_hash_after_watermark=sha256_bytes(b"normalized_after"),
            perceptual_hash_before_watermark="8f3a7b2c9e1d4f6a",
            perceptual_hash_after_watermark="1d6e9c4a8b3f7e2d",
            watermark_presence_expected=True,
            embedding_reference="embedding_001",
        )

        assert len(profile.exact_hash_before_watermark) == 64
        assert profile.watermark_presence_expected is True
        assert profile.embedding_reference == "embedding_001"


class TestWatermarkWorkflowScenarios:
    """Test real-world watermark workflow scenarios."""

    def test_text_document_watermarking(self):
        """Test complete workflow for text document watermarking."""
        # Original AI-generated text
        original_text = "This is a comprehensive AI-generated report about climate change..."

        # Apply watermark
        watermarked_text = original_text + "\n\n---\nGenerated by AI | Verify: vault.example.com"

        # Create watermark descriptor
        watermark = WatermarkDescriptor(
            watermark_id="wm_text_001",
            watermark_type=WatermarkType.VISIBLE,
            tag_text="Generated by AI | Verify: vault.example.com",
            verification_url="https://vault.example.com/verify/wm_text_001",
            removal_resistance="low",
            location="footer",
        )

        # Create forensic fragments
        frag1 = TextForensicFragment(
            fragment_id="frag_0_begin",
            fragment_type="text",
            entropy_score=0.87,
            sampling_method="begin",
            content_position=0,
            offset_start=0,
            offset_end=100,
            fragment_length=100,
            sample_location="beginning",
            fragment_text=original_text[0:100],
            fragment_hash_before=sha256_text(original_text[0:100]),
            fragment_hash_after=sha256_text(watermarked_text[0:100]),
        )

        fragment_set = ForensicFragmentSet(
            fragment_count=1,
            sampling_strategy="multi_point",
            total_coverage_percent=10.0,
            text_fragments=[frag1],
        )

        # Create hash set
        hashes = ArtifactHashSet(
            content_hash_before_watermark=sha256_text(original_text),
            content_hash_after_watermark=sha256_text(watermarked_text),
            forensic_fragments=fragment_set,
        )

        # Create evidence
        evidence = ArtifactEvidence(
            artifact_id="art_text_001",
            artifact_type=ArtifactType.TEXT,
            mime_type="text/plain",
            created_at=datetime.now(timezone.utc).isoformat(),
            model_id="gpt-4",
            model_version="4.0",
            actor_id="user_alice",
            prompt_hash=sha256_text("Write a report about climate change"),
            output_hash_raw=sha256_text(original_text),
            output_hash_distributed=sha256_text(watermarked_text),
            watermark=watermark,
            hashes=hashes,
        )

        assert evidence.artifact_type == ArtifactType.TEXT
        assert evidence.hashes.forensic_fragments is not None

    def test_image_watermarking_hybrid(self):
        """Test hybrid watermarking for images."""
        # Simulate image watermarking
        original_image = b"PNG_IMAGE_DATA_ORIGINAL"
        watermarked_image = b"PNG_IMAGE_DATA_WITH_WATERMARK_AND_METADATA"

        watermark = WatermarkDescriptor(
            watermark_id="wm_img_001",
            watermark_type=WatermarkType.HYBRID,
            tag_text="AI-Generated | ModelX v2.1",
            verification_url="https://vault.example.com/verify/wm_img_001",
            embed_method="LSB steganography + XMP metadata + visual corner tag",
            removal_resistance="high",
            location="bottom_right + metadata + LSB",
        )

        hashes = ArtifactHashSet(
            content_hash_before_watermark=sha256_bytes(original_image),
            content_hash_after_watermark=sha256_bytes(watermarked_image),
            perceptual_hash_before="8f3a7b2c9e1d4f6a",
            perceptual_hash_after="8f3a7b2c9e1d4f6b",  # Very similar
        )

        evidence = ArtifactEvidence(
            artifact_id="art_img_001",
            artifact_type=ArtifactType.IMAGE,
            mime_type="image/png",
            created_at=datetime.now(timezone.utc).isoformat(),
            model_id="stable-diffusion-v3",
            model_version="3.0.1",
            actor_id="user_bob",
            prompt_hash=sha256_text("A sunset over mountains"),
            output_hash_raw=sha256_bytes(original_image),
            output_hash_distributed=sha256_bytes(watermarked_image),
            watermark=watermark,
            hashes=hashes,
        )

        assert evidence.watermark.watermark_type == WatermarkType.HYBRID
        assert evidence.watermark.removal_resistance == "high"


class TestCanonicalJsonHashing:
    """Test canonical JSON serialization for hashing."""

    def test_canonical_json_deterministic(self):
        """Test canonical JSON produces deterministic output."""
        data1 = {"b": 2, "a": 1, "c": 3}
        data2 = {"c": 3, "a": 1, "b": 2}

        json1 = canonical_json(data1)
        json2 = canonical_json(data2)

        assert json1 == json2  # Order-independent

    def test_hash_utility_functions(self):
        """Test SHA-256 hash utility functions."""
        text = "Hello, World!"
        text_bytes = text.encode("utf-8")

        hash1 = sha256_text(text)
        hash2 = sha256_bytes(text_bytes)

        assert hash1 == hash2
        assert len(hash1) == 64  # SHA-256 hex digest


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
