#!/usr/bin/env python3
"""
CIAF Watermarks - PDF Visual Watermarking Example

Demonstrates PDF watermarking with QR codes in footer.

This example shows:
1. Creating a sample PDF
2. Adding QR code to footer with page numbers
3. Optional text stamp
4. Different QR positions
5. Multi-page PDF watermarking

Usage:
    python examples/example_pdf_visual_watermarking.py

Output:
    Creates watermarked PDFs in ./output/ directory

Created: 2026-03-30
Author: Denzil James Greenwood
Version: 1.0.0
"""

import sys
from pathlib import Path
from io import BytesIO

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import letter
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    print("⚠️  reportlab not installed. Install with: pip install reportlab")
    sys.exit(1)

from ciaf.watermarks.pdf.visual import (
    build_pdf_artifact_with_visual_watermark,
)


def create_sample_document(title: str, num_pages: int = 1) -> bytes:
    """Create a realistic sample PDF document."""
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    
    for page_num in range(1, num_pages + 1):
        # Title
        c.setFont("Helvetica-Bold", 20)
        c.drawString(72, 720, title)
        
        # Subtitle
        c.setFont("Helvetica", 12)
        c.drawString(72, 695, f"Generated by AI Model GPT-4 | Page {page_num} of {num_pages}")
        
        # Separator line
        c.line(72, 685, 540, 685)
        
        # Content
        c.setFont("Helvetica", 11)
        y = 660
        
        content_lines = [
            "This document was generated by an AI model and contains watermarking",
            "for provenance tracking and verification purposes.",
            "",
            "The watermark includes:",
            "  • QR code in footer for quick verification",
            "  • Page numbers for reference",
            "  • Embedded metadata for forensic analysis",
            "  • Cryptographic signatures for integrity",
            "",
            "To verify this document, scan the QR code or visit the verification URL.",
            "The CIAF (Cognitive Insight AI Framework) system ensures full traceability",
            "from prompt to final output, maintaining an immutable audit trail.",
            "",
            "Document Characteristics:",
            "  • Artifact Type: PDF Document",
            "  • Watermark Type: Visual (QR Code + Metadata)",
            "  • Removal Resistance: High",
            "  • Verification Method: Online + Offline",
        ]
        
        for line in content_lines:
            c.drawString(72, y, line)
            y -= 15
        
        # Add some more content to fill the page
        y -= 20
        c.setFont("Helvetica", 10)
        c.setFillColorRGB(0.4, 0.4, 0.4)
        
        for i in range(15):
            c.drawString(72, y, f"Sample content line {i+1}: This is additional text to demonstrate PDF watermarking.")
            y -= 12
            if y < 100:  # Leave space for footer
                break
        
        c.showPage()
    
    c.save()
    buffer.seek(0)
    return buffer.getvalue()


def example_1_basic_qr_watermark():
    """Example 1: Basic QR watermark in footer (bottom-right)."""
    print("\n" + "="*60)
    print("EXAMPLE 1: Basic QR Watermark (Bottom-Right)")
    print("="*60)
    
    # Create sample PDF
    pdf_bytes = create_sample_document("AI Generated Report", num_pages=1)
    
    # Apply watermark
    evidence, watermarked_pdf = build_pdf_artifact_with_visual_watermark(
        pdf_bytes=pdf_bytes,
        model_id="gpt-4",
        model_version="2026-03",
        actor_id="user:example",
        prompt="Generate a comprehensive report on AI watermarking",
        verification_base_url="https://vault.cognitiveinsight.ai",
        qr_position="bottom-right",  # Default
        qr_size=0.5,  # 0.5 inches
        add_page_numbers=True,
    )
    
    # Save output
    output_dir = Path("./output")
    output_dir.mkdir(exist_ok=True)
    
    output_path = output_dir / "example_1_basic_qr.pdf"
    output_path.write_bytes(watermarked_pdf)
    
    print(f"✅ Created: {output_path}")
    print(f"   Artifact ID: {evidence.artifact_id}")
    print(f"   Watermark ID: {evidence.watermark.watermark_id}")
    print(f"   Verification URL: {evidence.watermark.verification_url}")
    print(f"   QR Position: {evidence.metadata['qr_position']}")


def example_2_qr_bottom_left():
    """Example 2: QR code in bottom-left with page numbers."""
    print("\n" + "="*60)
    print("EXAMPLE 2: QR Watermark (Bottom-Left)")
    print("="*60)
    
    pdf_bytes = create_sample_document("Technical Documentation", num_pages=1)
    
    evidence, watermarked_pdf = build_pdf_artifact_with_visual_watermark(
        pdf_bytes=pdf_bytes,
        model_id="gpt-4",
        model_version="2026-03",
        actor_id="user:example",
        prompt="Create technical documentation",
        verification_base_url="https://vault.cognitiveinsight.ai",
        qr_position="bottom-left",
        qr_size=0.6,
        add_page_numbers=True,
    )
    
    output_path = Path("./output/example_2_qr_left.pdf")
    output_path.write_bytes(watermarked_pdf)
    
    print(f"✅ Created: {output_path}")
    print(f"   QR Position: bottom-left")


def example_3_qr_with_text_stamp():
    """Example 3: QR code with additional text stamp."""
    print("\n" + "="*60)
    print("EXAMPLE 3: QR + Text Stamp")
    print("="*60)
    
    pdf_bytes = create_sample_document("Confidential Report", num_pages=1)
    
    evidence, watermarked_pdf = build_pdf_artifact_with_visual_watermark(
        pdf_bytes=pdf_bytes,
        model_id="gpt-4",
        model_version="2026-03",
        actor_id="user:example",
        prompt="Generate confidential report",
        verification_base_url="https://vault.cognitiveinsight.ai",
        qr_position="bottom-right",
        qr_size=0.5,
        add_page_numbers=True,
        add_text_stamp=True,
        stamp_text="AI GENERATED - VERIFY AT vault.cognitiveinsight.ai",
    )
    
    output_path = Path("./output/example_3_qr_with_stamp.pdf")
    output_path.write_bytes(watermarked_pdf)
    
    print(f"✅ Created: {output_path}")
    print(f"   Has text stamp: {evidence.metadata['has_text_stamp']}")


def example_4_multi_page():
    """Example 4: Multi-page document with QR on all pages."""
    print("\n" + "="*60)
    print("EXAMPLE 4: Multi-Page Document")
    print("="*60)
    
    pdf_bytes = create_sample_document("Research Paper", num_pages=5)
    
    evidence, watermarked_pdf = build_pdf_artifact_with_visual_watermark(
        pdf_bytes=pdf_bytes,
        model_id="gpt-4",
        model_version="2026-03",
        actor_id="user:example",
        prompt="Write a research paper on AI provenance",
        verification_base_url="https://vault.cognitiveinsight.ai",
        qr_position="bottom-center",
        qr_size=0.4,
        add_page_numbers=True,
    )
    
    output_path = Path("./output/example_4_multi_page.pdf")
    output_path.write_bytes(watermarked_pdf)
    
    print(f"✅ Created: {output_path}")
    print(f"   Pages: 5")
    print(f"   QR Position: bottom-center")
    print(f"   Each page has QR code + page number")


def example_5_comparison():
    """Example 5: Create all three positions for comparison."""
    print("\n" + "="*60)
    print("EXAMPLE 5: Position Comparison")
    print("="*60)
    
    positions = ["bottom-left", "bottom-center", "bottom-right"]
    
    for position in positions:
        pdf_bytes = create_sample_document(f"QR Position: {position.title()}", num_pages=1)
        
        evidence, watermarked_pdf = build_pdf_artifact_with_visual_watermark(
            pdf_bytes=pdf_bytes,
            model_id="gpt-4",
            model_version="2026-03",
            actor_id="user:example",
            prompt=f"Test {position}",
            verification_base_url="https://vault.cognitiveinsight.ai",
            qr_position=position,
            qr_size=0.5,
            add_page_numbers=True,
        )
        
        output_path = Path(f"./output/example_5_position_{position.replace('-', '_')}.pdf")
        output_path.write_bytes(watermarked_pdf)
        
        print(f"✅ Created: {output_path}")


def main():
    """Run all examples."""
    print("\n" + "="*60)
    print("CIAF PDF VISUAL WATERMARKING EXAMPLES")
    print("="*60)
    print("\nThese examples demonstrate PDF watermarking with QR codes.")
    print("All outputs will be saved to ./output/ directory.\n")
    
    try:
        example_1_basic_qr_watermark()
        example_2_qr_bottom_left()
        example_3_qr_with_text_stamp()
        example_4_multi_page()
        example_5_comparison()
        
        print("\n" + "="*60)
        print("✅ ALL EXAMPLES COMPLETE")
        print("="*60)
        print("\nOutput files created in ./output/:")
        print("  • example_1_basic_qr.pdf")
        print("  • example_2_qr_left.pdf")
        print("  • example_3_qr_with_stamp.pdf")
        print("  • example_4_multi_page.pdf")
        print("  • example_5_position_*.pdf (3 files)")
        print("\nOpen these files to see the QR codes in action!")
        print("Scan the QR codes with your phone to verify the artifacts.")
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        return 1
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
